### PR TITLE
Ignore invalid commits

### LINKED ISSUE #1: Using my username ends with an error
``` js
devTime('gillstrom')
    .then(console.log)
    .catch(console.error);
```

Ends with the error below:

```
Error: Command failed: git log -1 --format="%aI" a48ada0d6939c14c9555551a3ff850e17be41cd1 fatal: bad object a48ada0d6939c14c9555551a3ff850e17be41cd1
```

Using a username like `kevva` works fine. My guess is this is happening because I [deleted the branch containing the commit](https://help.github.com/articles/commit-exists-on-github-but-not-in-my-local-clone/).

### PR DESCRIPTION
**Pull request by kevva**
Fixes #1.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Thanks for the PR, not sure if it fixes #1 entirely as the `git log` command uses the `sha` string to filter on. Wdyt?

**Comment by kevva** [comment]
Hm, what do you mean exactly? This seems to fix the specific case mentioned in #1 at least.

**Comment by SamVerschueren** [comment]
It indeed returns a timestamp, but actually that is just your current local time which is probably by coincidence the same as @gillstrom

The output of this command is empty.

```
$ git log -1 --format="%aI" --ignore-missing a48ada0d6939c14c9555551a3ff850e17be41cd1`
```

This is because the commit with sha `a48ada0d6939c14c9555551a3ff850e17be41cd1` does not exist anymore in the `git log` so it cannot parse the timestamp of the commit anymore.

**Comment by kevva** [comment]
Oh, that's true. So what's the ideal solution here? Get the next latest push or something?

**Comment by SamVerschueren** [comment]
It should be fixed in [latest-push](https://github.com/samverschueren/latest-push) I guess. But not sure if it's easy to fix. The API result of commit [a48ada0d6939c14c9555551a3ff850e17be41cd1](https://api.github.com/repos/gillstrom/anything.js/commits/a48ada0d6939c14c9555551a3ff850e17be41cd1) does not return a property `exists` or something. So it's not possible to detect the existance of the commit.

A fix could be to add an `exclude` property in `latest-push` where you can pass in an array of event id`s that will be excluded.

``` js
latestPush('gillstrom', {exclude: ['3412183258']}).then(function (result) {
    //=> The next push event
});
```

If the `git log` command returns an empty result for that push event as well, just add that event to the exclude array and do it again.

``` js
latestPush('gillstrom', {exclude: ['3412183258', '3412183259']}).then(function (result) {
    //=> The next push event
});
```

Have to think again about it but don't see any other possibility to solve this at the moment. If you have any other ideas, feel free to share :).

**Comment by SamVerschueren** [comment]
fixed in `v0.2.1`.

**Pull request closed without merging**
