### PR TITLE
Tweaks

### LINKED ISSUE #5: Occasionally throws Error: ENOTEMPTY: directory not empty
Occasionally, clearing the Git repo fails with:

``` shell
❯ ./node_modules/.bin/dev-time kentcdodds
Error: ENOTEMPTY: directory not empty, rmdir '/var/folders/_n/vc1rw4250cbb96q5pfkflndw0000gn/T/4b50bef2-ffa6-4d65-b43d-01906829b456/.git'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at rmkidsSync (/private/tmp/node_modules/rimraf/rimraf.js:334:11)
    at rmdirSync (/private/tmp/node_modules/rimraf/rimraf.js:324:7)
    at rimrafSync (/private/tmp/node_modules/rimraf/rimraf.js:295:9)
    at /private/tmp/node_modules/rimraf/rimraf.js:332:5
    at Array.forEach (native)
    at rmkidsSync (/private/tmp/node_modules/rimraf/rimraf.js:331:26)
    at rmdirSync (/private/tmp/node_modules/rimraf/rimraf.js:324:7)
    at Function.rimrafSync [as sync] (/private/tmp/node_modules/rimraf/rimraf.js:295:9)
```

If I run that a second time, often no error is thrown; this happens with arbitrary GitHub usernames.

dev-time-cli v1.3.2 (which pulls in dev-time 0.4.0), OS X 10.10.5.

### LINKED ISSUE #7: Consider using `del` instead of `del.sync`
`del.sync` uses `rimraf.sync`, about which isaacs says:

> It can remove stuff synchronously, too. But that's not so good. Use the async API. It's better.

However, I don't know in which way it is better…

### PR DESCRIPTION
**Pull request by schnittstabil**
Closes #7 and probably fixes #5.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Will look into it tomorrow (or monday). Not much time a.t.m. Ping me back if I haven't :). Thanks for the effort!

**Comment by SamVerschueren** [comment]
@schnittstabil Maybe we should use [execa](https://github.com/sindresorhus/execa) instead of `child_process.execFile`?

**Comment by schnittstabil** [comment]
No problem, but we have to drop support for [`node < v0.12`](https://github.com/sindresorhus/execa/blob/master/package.json#L13), if that's ok.

**Comment by SamVerschueren** [comment]
Mmh, that's probably the reason why I didn't use it before. I'm ok with dropping it for CLI's but not yet for programming API's.

So I'm good with how it looks at the moment. Probably `execa` doesn't support `0.10` because of the Promise thing. `global.Promise = require('pinkie-promise');` might be enough to get it working.

**Comment by schnittstabil** [comment]
Maybe, but `execa` is not tested against `node < v0.12` and nobody knows what the future holds…

**Comment by SamVerschueren** [comment]
Good point, we'll keep it like this and might drop support in the future. Thanks for the PR :).

**Pull request merged**
